---
title: "Illinois"
output: 
  rmdformats::downcute:
    toc_depth: 3
---


# Overview

```{r setup, include=FALSE}

source('helper_functions.R')
load_packages()



```



```{r message=FALSE, warning=FALSE, include=FALSE}


hifld_df <- st_read("utility_zones/HIFLD/Electric_Retail_Service_Territories (1)/Electric_Retail_Service_Territories.shp") 

state_list <- c("IL", "MA", "MN", "NJ", "NM", "NY",  "CA", "DE")


temp_util <- hifld_df %>%
  filter(ID %in% c(56697, 4110,12341)) %>%
  mutate(new_name = case_when(
    ID == 56697 ~ "Ameren",
    ID == 4110 ~ "ComEd",
    ID == 12341 ~ "MidAmerican"
  ))

get_tracts <- get_acs(
  geography="tract", 
  state=state_list,
  variables=c("total_pop" = "B01001_001"),
  year=2019, 
  geometry=TRUE) %>%
  mutate(total_pop = estimate) %>%
  select(geoid=GEOID, geometry, total_pop)


```



## Geoqualification





```{r message=FALSE, warning=FALSE, include=FALSE}
chas_df <- load_chas() %>%
    mutate(State_Name = case_when(
    state == 17 ~ "Illinois",
    state == 25 ~ "Massachusetts",  
    state == 27 ~ "Minnesota",  
    state == 34 ~ "New Jersey",
    state == 35 ~ "New Mexico",  
    state == 36 ~ "New York",
    state == 06 ~ "California",
    TRUE ~ "Other"
  ))

il_counties <- get_acs(geography="county",
                       variables = c(totapop = "B01003_001"), 
              state = "IL", 
              year = 2021,
              geometry = TRUE)



add_geo <- merge(chas_df, get_tracts) 

add_geo <- st_as_sf(add_geo)

il_geo <- add_geo %>%
  filter(State_Name=="Illinois")

temp_util <- st_transform(temp_util, st_crs(il_geo)) %>%
  st_make_valid()
```

## LMI Qualification


* 80% AMI

```{r echo=FALSE, message=FALSE, warning=FALSE}

pal5 <- colorFactor(
  palette="viridis",
  domain=temp_util$new_name
)

il_counties <- il_counties %>%
  filter(GEOID == 17073 | GEOID == 17131)

leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(data=temp_util,
              group="Utility Zones",
              stroke=TRUE,
              color=~pal5(temp_util$new_name),
              dashArray="3",
              fillOpacity=0.25,
              popup=paste("Utility Zone: ", temp_util$new_name)) %>%
  addLegend(position="bottomright",
            pal=pal5,
            values=temp_util$new_name,
            title="Solstice IL Utilities") %>%
  addPolygons(data=il_counties, 
              stroke=TRUE,
              color="black",
              dashArray="3",
              group="Counties",
              fillOpacity=0,
              popup=paste("Utility Zone: ", il_counties$NAME)) %>%
  # addPolygons(data = il_tracts,
  #             color = "red",
  #             fillOpacity = .5,
  #             popup=paste("GEOID: ", il_tracts$geoid)) %>%
  
  
  addLayersControl(
    overlayGroups=c( "Counties", "Utility Zones"),  # Update the order for consistency
    options = layersControlOptions(collapsed = FALSE)
  )
```




### Total Pop/HH Coverage



```{r message=FALSE, warning=FALSE, include=FALSE}
# Specify the variables you're interested in
vars <- c("B01003_001",# total population
          "B11001_001", # total households
          "B25003_001" # total occupied households
          ) 

# Retrieve population data for Mercer County, Illinois
mercer_data <- get_decennial(
  geography = "block",
  variables = c("total_pop" = "P1_001N",
                "total_hh" = "H1_001N",
                "total_occ_hh" = "H1_002N"),
  state = "IL",
  county = c("131"),
  year = 2020,
  geometry = TRUE
) %>%
  group_by(GEOID) %>%
  summarize(
    total_pop = value[variable == "total_pop"],
    total_hh = value[variable == "total_hh"],
    total_occ_hh = value[variable == "total_occ_hh"]
  )
# Retrieve population data for Henry County, Illinois

henry_data <- get_decennial(
  geography = "block",
  variables = c("total_pop" = "P1_001N",
                "total_hh" = "H1_001N",
                "total_occ_hh" = "H1_002N"),
  state = "IL",
  county = c("073"),
  year = 2020,
  geometry = TRUE
) %>%
  group_by(GEOID) %>%
  summarize(
    total_pop = value[variable == "total_pop"],
    total_hh = value[variable == "total_hh"],
    total_occ_hh = value[variable == "total_occ_hh"]
  )


```





```{r echo=FALSE, message=FALSE, warning=FALSE}
## Mercer Demographic Table

total_hh <- sum(mercer_data$total_hh)

temp <- mercer_data %>% 
  st_point_on_surface() %>%
  st_make_valid() %>%
  st_join(temp_util %>% select(NAME)) %>%
  st_drop_geometry() %>%
  group_by(Name = NAME) %>%
  filter(!is.na(Name)) %>%
  summarize(`Total HH` = sum(total_hh),
            `Total Occupied HH` = sum(total_occ_hh),
            `Total Population` = sum(total_pop)) %>%
  adorn_totals("row") %>%
  mutate('Total HH Pct' = `Total HH` / sum(mercer_data$total_hh),
         'Total HH Occupied Pct' = `Total Occupied HH` / sum(mercer_data$total_occ_hh) ,
         'Total Population Pct' = `Total Population` / sum(mercer_data$total_pop) )

datatable(temp, caption = "Mercer County, Sources: ACS 2019 and HUD CHAS")%>%
  formatCurrency('Total HH', currency = "", mark = ",", interval = 3, digits = 0) %>%
  formatCurrency('Total Occupied HH', currency = "", mark = ",", interval = 3, digits = 0) %>%
  formatCurrency('Total Population', currency = "", mark = ",", interval = 3, digits = 0) %>%
  formatPercentage('Total HH Pct',digits=2, interval = 3) %>%
  formatPercentage('Total HH Occupied Pct',digits=2, interval = 3) %>%
  formatPercentage('Total Population Pct',digits=2, interval = 3)




```




## LIFT Solar

```{r message=FALSE, warning=FALSE, include=FALSE}
il_tracts <- get_acs(
  geography="tract", 
  state="IL",
  variables=c("Total_Pop" = "B01001_001","snap_hh" = "B22001_002","snap_pop" = "B19058_002"
              
              ),
  year=2019, 
  geometry=TRUE) %>%
  group_by(GEOID) %>%
  summarize(total_pop = estimate[variable=="Total_Pop"],
            snap_hh = estimate[variable=="snap_hh"],
            snap_pop = estimate[variable=="snap_pop"])







total_il_tracts <- cbind(il_geo, il_tracts)

```



There are 13 community solar projects in New Jersey according to the LIFT solar database. 



```{r echo=FALSE, fig.height=10, fig.width=8, message=FALSE, warning=FALSE}

lift_df <- read.csv("data/groundswell_lift/cs-projects-2023-08-18.csv") 

lift_df <- separate(lift_df, GeoCode, into = c("long", "lat"), sep = ",")

lift_df <- st_as_sf(lift_df, coords = c("long", "lat"), crs = st_crs(get_tracts))



temp_df <- add_geo %>%
  filter(State_Name == "Illinois") 

temp_lift <- lift_df %>%
  filter(State == "Illinois")


pal_potLMI <- colorNumeric(
  palette = "viridis",
 # reverse=TRUE,
  domain = temp_lift$Potential...LMI.Subscribers)

pal_cap <- colorNumeric(
  palette = "viridis",
 # reverse=TRUE,
  domain = temp_lift$Project.Capacity.KW.AC)



pal <- colorNumeric(
  palette = "viridis",
 # reverse=TRUE,
  domain = temp_df$AMI_80)

pal2 <- colorNumeric(
  palette = "Purples",
 # reverse=TRUE,
  domain = temp_df$AMI_80_Pct)

pal3 <- colorNumeric(
  palette = "viridis",
 # reverse=TRUE,
  domain = total_il_tracts$snap_hh)

library(tidyr)





map <- leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(data=temp_util,
              group="Utility Zones",
              stroke=TRUE,
              color="black",
              dashArray="3",
              fillOpacity=0,
              popup=paste("Utility Zone: ", temp_util$comp_short)
  ) %>%
  
  addPolygons(
    data = temp_df,
    group="80% AMI",  # This should be consistent with the group name in the addLegend function
    stroke=FALSE,
    smoothFactor=0.2,
    fillOpacity=0.85,
    color=~pal(AMI_80),
    popup=paste("Tract: ", temp_df$geoid, "<br>", 
                "HHs at 80% AMI: ", temp_df$AMI_80)
  ) %>%

  addLegend("bottomleft",
            group="80% AMI",  # This should be consistent with the group name in the addPolygons function
            pal = pal,
            values = temp_df$AMI_80,
            title="Number of HHs at 80% AMI"
  ) %>%
  
  # addPolygons(
  #   data=nm_df,
  #   group="80% AMI Percent",  # This should be consistent with the group name in the addLegend function
  #   stroke=FALSE,
  #   smoothFactor=0.2,
  #   fillOpacity=0.7,
  #   color=~pal2(AMI_80_Pct),
  #   popup=paste("Tract: ", nm_df$geoid, "<br>", 
  #               "Percent of HHs at 80% AMI: ", nm_df$AMI_80_Pct)
  # ) %>%
  # 
  # addLegend("bottomleft",
  #           group="80% AMI Percent",  # This should be consistent with the group name in the addPolygons function
  #           pal = pal2,
  #           values = nm_df$AMI_80_Pct,
  #           title="Percent of HHs at 80% AMI"
  # ) %>%
  
  addPolygons(
    data=total_il_tracts,
    group="SNAP",
    stroke=FALSE,
    smoothFactor=0.2,
    fillOpacity=0.7,
    color=~pal3(snap_hh),
    popup=paste("Tract: ", total_il_tracts$GEOID, "<br>",
                "Number of HHs Receiving SNAP: ", total_il_tracts$snap_hh)
  ) %>%

  addLegend("bottomleft",
            group="SNAP",
            pal = pal3,
            values = total_il_tracts$snap_hh,
            title="Number of HHs Receiving SNAP:"
  ) %>%
  
    addCircleMarkers(data = temp_lift,
                   group="Potential LMI Subscribers",
                   popup = ~paste("Program Name: ", Program.Name, "<br>",
                                  "Developer/Owner: ", Project.Developer.or.Owner, "<br>", 
                                  "Project Capacity: ", Project.Capacity.KW.AC, "<br>",
                                  "LMI Savings: ", LMI.Customer.Savings.., "<br>",
                                  "Potential LMI Subscribers: ", Potential...LMI.Subscribers),
                   radius = sqrt(temp_lift$Potential...LMI.Subscribers), 
                   color = ~pal_potLMI(Potential...LMI.Subscribers)) %>%
  addLegend("bottomright",
            group="Potential LMI Subscribers",  # This should be consistent with the group name in the addPolygons function
            pal = pal_potLMI,
            values = temp_lift$Potential...LMI.Subscribers,
            title="Potential LMI Subscribers") %>%

    ## Project Capacity ## 
  
  addCircleMarkers(data = temp_lift,
                   group="Project Capacity",
                   popup = ~paste("Program Name: ", Program.Name, "<br>",
                                  "Developer/Owner: ", Project.Developer.or.Owner, "<br>", 
                                  "Project Capacity: ", Project.Capacity.KW.AC, "<br>",
                                  "LMI Savings: ", LMI.Customer.Savings.., "<br>",
                                  "Potential LMI Subscribers: ", Potential...LMI.Subscribers),
                   radius = sqrt(temp_lift$Project.Capacity.KW.AC), 
                   color = ~pal_cap(Project.Capacity.KW.AC)) %>%
  addLegend("topleft",
             group="Project Capacity",  # This should be consistent with the group name in the addPolygons function
            pal = pal_cap,
            values = temp_lift$Project.Capacity.KW.AC,
            title="Project Capacity") %>%


  addLayersControl(
    overlayGroups=c( "80% AMI", "Utility Zones", "SNAP","Potential LMI Subscribers", "Project Capacity"),  # Update the order for consistency
    options = layersControlOptions(collapsed = FALSE)
  )

map %>%
 hideGroup("SNAP") %>% hideGroup("80% AMI") %>% hideGroup("Project Capacity")

```

