---
title: "Home"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmdformats::downcute:
    toc_depth: 3
---


# Overview

This document summarizes the total addressable markets within each state Solstice operates or plans to explore. 

Each state defines eligible population for solar farms through unique programmatic details, listed in detail on the [Policy Matrix](https://coda.io/d/Solstice-Policy_dBUL-zOSfnb/Program-Matrix_suVJB#Program-Matrix_tuLIr/r11&view=full) on Coda. This work looks to define how many people are eligible for each state program via income, geographic, or other unique definitions. Many programs have LMI carveouts; this document looks to define how many people that equates to. When available and applicable, utiliy zones are overlaid with these populations to estimate the potential population Solstice would be competing to sign up. 

Utility coverage is provided by either the [HIFLD](https://hifld-geoplatform.opendata.arcgis.com/datasets/f4cd55044b924fed9bc8b64022966097/explore?location=41.065293%2C-80.583661%2C6.90) national level electric retail service territories or, preferably, state sources that are more granular. Note HIFLD often provides overlapping areas (ex: a municipal boundary and an utility provider) so data should primarily be sourced from state sources or be validated from HIFLD. 

# Parcel Coverage

Using parcel data, we can tag individual plots considered eligible by various state programs. When data is available, further analyses can provide breakdowns between residential and commercial buildings, allowing marketing to zero in on potential sites for a variety of applications such as corporation identification. Note, this process is only available in states where sufficient and open sourced parcel data is made available. Examples include [Illinois](https://jake-ford.github.io/lmi_by_utility_v2/Illinois.html). 

# Solar Saturation

We use the Groundswell's [LIFT](https://lift.groundswell.org/solar-projects/) to analyze existing CS market sizes and compare these to total capacity in the current state to arrive at existing capacity. State specific resources may supplement LIFT. 



# Total Eligible Population Comparison

```{r echo=FALSE, message=FALSE, warning=FALSE}
states <- c("New Mexico", "New Jersey", "New York", "Massachusetts",
            "Illinois", "Minnesota", "California", "Delaware")

geo_qualified <- c("No", "Yes", "Yes", "Yes", 
                   "Yes", "No?", "Yes", "Yes")




temp_table <- data.frame(States = states,
                         Geoqualification = geo_qualified)
library(DT)
datatable(temp_table)
```

