---
title: "2022 Reading List"
author:
  - name: Jacob Ford
    url: {}
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    self_contained: false
---



Less delicious than the food recommendations, but more so for the soul. My recent 2022 reading and listenings, yes I am a recent audiobook convert. Two I would highly recommend from the below: the biography of James A Baker III, which reads like a podcast version of the West Wing; and, sticking to the theme, Ron Silver aka Bruno Gianelli narration of Phillip Roth's masterpiece, Plot Against America. 

Other highlights: fanboying over Olga Tokarczuk. Also, I have a tendancy of reading multiple works by same author, finally got to Echo Maker after loving the Overstory; did not disappoint but did not surpass. And I've gone through five or so Phillip Roth pieces, starting with the unforgettable Portnoy's Complaint. But Plot Against America was stunning!  

October 2022 Update: I'm not sure where to put this, but my best friend recommended a few mangas. I've put my nose up long enough - dove into the Solo Leveling, absolutely gripping. Will continue and let you know, some 200 chapters later :) 

```{r echo=FALSE, message=FALSE, warning=FALSE}

library(kableExtra)

titles <- c('The Echo Maker',
'Klara and the Sun',
'The Man Who Ran Washington: The Life and Times of James A. Baker III',
'Churwell & Orwell: The Fight for Freedom',
'Flights',
'Plot Against America',
'Broken Earth Trilogy',
'Descrates Bones',
'The City and the City',
'Dutch House - Tom Hanks (!) narrated',
'Song of Achilles',
'Books of Jacob',
'Giovannis Room',
'The Witcher: The Last Wish',
'The Power',
'Civilizations: A Novel',
'Finding Me: A Memoir',
'Black Cake',
'Three Body Problem')

authors <- c(
'Richard Powers',
'Kazuo Ishiguro',
'Peter Baker & Susan Glasser',
'Thomas E. Ricks',
'Olga Tokarczuk',
'Phillip Roth',
'NK Jemisin',
'Russel Shorto',
'China Melville',
'Ann Patchett',
'Madeline Miller',
'Olga Tokarczuk (again)',
'James Baldwin',
'Andrzej Sapkowski',
'Naomi Alderman',
'Laurent Binet',
'Viola Davis',
'Charmaine Wilkerson',
'Liu Cixin'

)

reading_data <- data.frame(Title=titles,Author=authors)
                           

reading_data %>%
  kbl() %>%
  kable_classic(full_width = F, html_font = "Cambria")
# chas_data_11%>%
#   kbl(caption = "HUD CHAS 2014-2018 Houseolds by AMI",
#       digits = 3, format.args = list(big.mark = ",",scientific = FALSE)) %>%
#   kable_classic(full_width = F, html_font = "Cambria")
```

