---
title: "HOLC, Redlining and Our old Census Friend"
description: |
  centroids, centroids, centroids
author:
  - name: Jacob Ford
    url: {}
date: 2022-06-26
output:
  distill::distill_article:
    self_contained: false
---


# Introduction 

```{r message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(sf)
library(leaflet)

holc_lines <- st_read("fullshpfile/shapefile/holc_ad_data.shp")

durham_lines <- holc_lines %>%
  filter(state=="NC") %>%
  filter(city=="Durham")

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
library(nngeo)
library(sf)
library(leaflet)
library(PL94171)
library(janitor)
library(dplyr)
library(tidycensus)
library(tidyverse)
options(tigris_use_cache = TRUE)
library(sf)
library(data.table)
library(dplyr)
library(plotly)


# remotes::install_github("walkerke/tidycensus")
# remotes::install_github("walkerke/tigris")
library(tidycensus)
library(tidyverse)
library(tigris)

vars_2020 <- load_variables(2020,"pl",cache=TRUE)
vars_2010 <- load_variables(2010,"sf1", cache=TRUE)
vars_2019 <- load_variables(2019,"acs5", cache=TRUE)




zones <- st_read("Zoning.shp")







```
 
 
 

```{r message=FALSE, warning=FALSE, include=FALSE}
res_words <- paste("RESIDENTIAL", "RES", sep = "|")

commerical_words <- paste("COMMECIAL", "COMMERCIAL", "UNIVERSITY","OFFICE", "INDUST", "MIXED", 'COMPACT',sep = "|")

downtown_words <- paste("DOWNTOWN")

  
zones <- zones %>%
  mutate(
    zone_flag = case_when(
      grepl("COMPACT", ZONE_GEN) ~ "Compact",
      is.na(ZONE_GEN) ~ "University",
      grepl(downtown_words, ZONE_GEN) ~ "Downtown",
      grepl(commerical_words, ZONE_GEN) ~ "Commerical",
      grepl(res_words, ZONE_GEN) ~ "Residential",
      
      TRUE ~ "Other"
      )
    )


table(zones$zone_flag)
```

```{r message=FALSE, warning=FALSE, include=FALSE}




pal <- colorFactor(
  palette='Dark2',
  domain=zones$zone_flag
)

zone_map <- leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  setView(-78.90390102117877,35.998220055791876,  zoom=14)%>%
  addPolygons(data=zones,
              weight=1,
              color=~pal(zone_flag),
              popup=paste("Zone Type: ", zones$zone_flag, "<br>",
                          "Detailed Zone:", zones$ZONE_GEN)) %>%
  addLegend(
    position="bottomright",
    pal=pal,
    values=zones$zone_flag
  )


zone_map
```



## Collapsed Zone Density 

```{r echo=FALSE, message=FALSE, warning=FALSE}


res_zones <- zones %>%
#  filter(zone_flag == "Residential" | zone_flag=="Compact") %>%
 # filter(ZONE_GEN != "RESEARCH") %>%
  mutate(
    density = case_when(
     grepl("RURAL", ZONE_GEN)  ~ "Rural Density",
     ZONE_GEN == "RES_LOW_DENSITY" ~ "Low Density",
     ZONE_GEN == "RES_MEDIUM_DENSITY" ~ "Medium Density",
     ZONE_GEN == "RES_HIGH_DENSITY" ~ "High Density",
     grepl("COMPACT", ZONE_GEN) ~ "Compact",
     grepl("DOWNTOWN", ZONE_GEN) ~ "Downtown"
      ),
    dwell_units = case_when (
      density == "Rural Density" ~  0.75,
      density == "Low Density" ~  4,
      density == "Medium Density" ~  9,
      density == "High Density" ~ 36,
      density == "Compact" ~ 75,
      density == "Downtown" ~ 75
    )
    )


pal <- colorFactor(
  palette='Dark2',
  domain=res_zones$density
)

zone_map <- leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  setView(-78.90390102117877,35.998220055791876,  zoom=14)%>%
  addPolygons(data=res_zones,
              weight=1,
              color=~pal(density),
              popup=paste("Zone Type: ", res_zones$zone_flag, "<br>",
                          "Detailed Zone:", res_zones$density, "<br>",
                          "Zoned for ", res_zones$dwell_units, "Dwell Units maximum", "<br>",
                          "Acres: ", res_zones$ACRES)) %>%
  addLegend(
    position="bottomright",
    pal=pal,
    values=res_zones$density
  )


zone_map

```




## HOLC Lines

[Source](https://data.diversitydatakids.org/dataset/holc_census_tracts-home-owner-loan-corporation--holc--neighborhood-grades-for-us-census-tracts)

```{r echo=FALSE, message=FALSE, warning=FALSE}

pal <- colorFactor(
  palette=c("green","blue", "yellow", "red"),
  domain=durham_lines$holc_grade
)

holc_map <- leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  setView(-78.90390102117877,35.998220055791876,  zoom=14)%>%
  addPolygons(data=durham_lines,
              weight=1,
              color=~pal(holc_grade),
              popup=paste("HOLC Grade: ", durham_lines$holc_grade, "<br>")) %>%
  addLegend(
    position="bottomright",
    pal=pal,
    values=durham_lines$holc_grade
  )


holc_map


  
  

```



### Combine Zoning & HOLC



```{r echo=FALSE, message=FALSE, warning=FALSE}
pal <- colorFactor(
  palette='Dark2',
  domain=res_zones$density
)

pal_holc <- colorFactor(
  palette=c("green","blue", "yellow", "red"),
  domain=durham_lines$holc_grade
)

combined_map <- leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  setView(-78.90390102117877,35.998220055791876,  zoom=14)%>%
  addPolygons(data=res_zones,
              group="Zoning",
              weight=1,
              color=~pal(density),
              popup=paste("Zone Type: ", res_zones$zone_flag, "<br>",
                          "Detailed Zone:", res_zones$density, "<br>",
                          "Zoned for ", res_zones$dwell_units, "Dwell Units maximum", "<br>",
                          "Acres: ", res_zones$ACRES)) %>%
    addPolygons(data=durham_lines,
              group="HOLC",
              weight=1,
              color=~pal_holc(holc_grade),
              popup=paste("HOLC Grade: ", durham_lines$holc_grade, "<br>")) %>%
  addLegend(
    position="bottomright",
    group="Zoning",
    pal=pal,
    values=res_zones$density
  ) %>%
  
    addLegend(
    position="bottomright",
    group="HOLC",
    pal=pal_holc,
    values=durham_lines$holc_grade
  ) %>%


  addLayersControl(overlayGroups = c("Zoning", "HOLC"))

combined_map %>% hideGroup("Zoning") 


```



Further analysis questions:

1. using centroid tagging, what is the proportion of Durham zones that are represented by HOLC letters? i.e. are 80% low density homes in A grade zones? 

2. what about census population, census demograhpic + income characteristics? 

working progress but very interesting. 

